# Generated by Django 5.2.5 on 2025-08-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Số tiền')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thanh toán')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Thẻ tín dụng'), ('bank_transfer', 'Chuyển khoản ngân hàng'), ('e_wallet', 'Ví điện tử'), ('other', 'Khác')], max_length=20, verbose_name='Phương thức thanh toán')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='Mã giao dịch')),
                ('status', models.CharField(choices=[('success', 'Thành công'), ('failed', 'Thất bại'), ('pending', 'Chờ xử lý')], default='pending', max_length=10, verbose_name='Trạng thái')),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'db_table': 'payment',
            },
        ),
    ]
