# Generated by Django 5.2.5 on 2025-11-06 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        ('policies', '0004_remove_policy_claimed_amount_policy_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Thẻ tín dụng'), ('bank_transfer', 'Chuyển khoản ngân hàng'), ('e_wallet', 'Ví điện tử'), ('money', 'Tiền mặt'), ('other', 'Khác')], max_length=20, verbose_name='Phương thức thanh toán'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='policies.policy', verbose_name='Hợp đồng bảo hiểm'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('success', 'Thành công'), ('failed', 'Thất bại'), ('pending', 'Chờ xử lý'), ('refunded', 'Đã hoàn tiền')], default='pending', max_length=10, verbose_name='Trạng thái'),
        ),
    ]
