# Generated by Django 5.2.5 on 2025-10-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], default='other', max_length=10, verbose_name='Giới tính'),
        ),
        migrations.AddField(
            model_name='customer',
            name='job',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nghề nghiệp'),
        ),
    ]
