# Generated by Django 5.2.5 on 2025-11-06 14:11

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer_gender_customer_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'agent'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản đại lý')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã đại lý')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ngân hàng')),
                ('bank_account_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Số tài khoản')),
                ('bank_account_holder', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên chủ tài khoản')),
            ],
            options={
                'verbose_name': 'Đại lý / Cộng tác viên',
                'verbose_name_plural': 'Đại lý / Cộng tác viên',
                'db_table': 'agents',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='cccd_back',
            field=models.FileField(blank=True, null=True, upload_to=users.models.upload_cccd_back),
        ),
        migrations.AddField(
            model_name='customer',
            name='cccd_front',
            field=models.FileField(blank=True, null=True, upload_to=users.models.upload_cccd_front),
        ),
        migrations.AddField(
            model_name='customer',
            name='ocr_verified',
            field=models.BooleanField(default=False, verbose_name='Đã xác minh eKYC'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Khách hàng'), ('employee', 'Nhân viên'), ('agent', 'Đại lí'), ('admin', 'Quản trị viên')], default='customer', max_length=10, verbose_name='Loại người dùng'),
        ),
    ]
