# Generated by Django 5.2.5 on 2025-08-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=50, unique=True, verbose_name='Số hợp đồng')),
                ('start_date', models.DateField(verbose_name='Ngày hiệu lực')),
                ('end_date', models.DateField(verbose_name='Ngày hết hạn')),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Phí bảo hiểm')),
                ('payment_status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('overdue', 'Quá hạn'), ('cancelled', 'Đã hủy')], default='pending', max_length=10, verbose_name='Trạng thái thanh toán')),
                ('policy_status', models.CharField(choices=[('active', 'Đang hoạt động'), ('expired', 'Đã hết hạn'), ('cancelled', 'Đã hủy'), ('pending', 'Chờ xử lý')], default='pending', max_length=10, verbose_name='Trạng thái hợp đồng')),
                ('policy_document_url', models.URLField(blank=True, verbose_name='URL tài liệu hợp đồng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Hợp đồng bảo hiểm',
                'verbose_name_plural': 'Hợp đồng bảo hiểm',
                'db_table': 'policies',
            },
        ),
        migrations.CreateModel(
            name='PolicyHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('date_of_birth', models.DateField(verbose_name='Ngày sinh')),
                ('id_card_number', models.CharField(max_length=20, verbose_name='Số CMND/CCCD')),
                ('relationship_to_customer', models.CharField(max_length=50, verbose_name='Mối quan hệ với khách hàng')),
            ],
            options={
                'verbose_name': 'Người được bảo hiểm',
                'verbose_name_plural': 'Người được bảo hiểm',
                'db_table': 'policyholders',
            },
        ),
    ]
