# Generated by Django 5.2.7 on 2025-10-05 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance_products', '0001_initial'),
        ('policies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer', verbose_name='Khách hàng'),
        ),
        migrations.AddField(
            model_name='policy',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_products.insuranceproduct', verbose_name='Sản phẩm bảo hiểm'),
        ),
        migrations.AddField(
            model_name='policyholder',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.policy', verbose_name='Hợp đồng bảo hiểm'),
        ),
    ]
