# Generated by Django 5.2.5 on 2025-10-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='claimed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tổng số tiền đã chi trả'),
        ),
        migrations.AddField(
            model_name='policy',
            name='sum_insured',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=12, verbose_name='Tổng số tiền bảo hiểm'),
            preserve_default=False,
        ),
    ]
