# Generated by Django 5.2.5 on 2025-11-06 14:11

import django.db.models.deletion
import policies.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_policy_claimed_amount_policy_sum_insured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='claimed_amount',
        ),
        migrations.AddField(
            model_name='policy',
            name='agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_policies', to=settings.AUTH_USER_MODEL, verbose_name='CTV bán'),
        ),
        migrations.AddField(
            model_name='policy',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Hoa hồng thực tế (VNĐ)'),
        ),
        migrations.AddField(
            model_name='policyholder',
            name='cccd_back',
            field=models.FileField(blank=True, null=True, upload_to=policies.models.upload_cccd_back),
        ),
        migrations.AddField(
            model_name='policyholder',
            name='cccd_front',
            field=models.FileField(blank=True, null=True, upload_to=policies.models.upload_cccd_front),
        ),
        migrations.AddField(
            model_name='policyholder',
            name='health_certificate',
            field=models.FileField(blank=True, null=True, upload_to=policies.models.upload_health_certificate, verbose_name='Giấy khám sức khỏe'),
        ),
        migrations.AddField(
            model_name='policyholder',
            name='selfie',
            field=models.FileField(blank=True, null=True, upload_to=policies.models.upload_selfie),
        ),
        migrations.AlterField(
            model_name='policy',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Ngày hết hạn'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Ngày hiệu lực'),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Số CMND/CCCD'),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='policies.policy', verbose_name='Hợp đồng bảo hiểm'),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='relationship_to_customer',
            field=models.CharField(choices=[('spouse', 'Vợ/Chồng'), ('child', 'Con'), ('parent', 'Cha/Mẹ'), ('sibling', 'Anh/Chị/Em'), ('me', 'Chính mình')], max_length=50, verbose_name='Mối quan hệ với khách hàng'),
        ),
        migrations.CreateModel(
            name='HealthInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(verbose_name='Chiều cao (cm)')),
                ('weight', models.PositiveIntegerField(verbose_name='Cân nặng (kg)')),
                ('smoker', models.CharField(choices=[('never', 'Không hút'), ('former', 'Đã bỏ'), ('current', 'Đang hút')], max_length=20, verbose_name='Hút thuốc')),
                ('alcohol', models.CharField(choices=[('no', 'Không'), ('sometimes', 'Thỉnh thoảng')], max_length=20, verbose_name='Uống rượu/bia')),
                ('conditions', models.JSONField(default=list, verbose_name='Tiền sử bệnh lý')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy_holder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_info', to='policies.policyholder', verbose_name='Người được bảo hiểm')),
            ],
            options={
                'verbose_name': 'Thông tin sức khỏe',
                'verbose_name_plural': 'Thông tin sức khỏe',
                'db_table': 'health_info',
            },
        ),
    ]
