# Generated by Django 5.2.7 on 2025-10-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi yêu cầu')),
                ('incident_date', models.DateField(verbose_name='Ngày xảy ra sự cố')),
                ('description', models.TextField(verbose_name='Mô tả sự cố')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Số tiền yêu cầu')),
                ('claim_status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('in_progress', 'Đang xử lý'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('settled', 'Đã giải quyết')], default='pending', max_length=15, verbose_name='Trạng thái yêu cầu')),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Số tiền được duyệt')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Lý do từ chối')),
                ('settlement_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày giải quyết')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Yêu cầu bồi thường',
                'verbose_name_plural': 'Yêu cầu bồi thường',
                'db_table': 'claims',
            },
        ),
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50, verbose_name='Loại tài liệu')),
                ('file_url', models.URLField(verbose_name='URL file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
                ('ocr_extracted_text', models.TextField(blank=True, verbose_name='Văn bản OCR')),
                ('ai_analysis_result', models.JSONField(default=dict, verbose_name='Kết quả phân tích AI')),
            ],
            options={
                'verbose_name': 'Tài liệu bồi thường',
                'verbose_name_plural': 'Tài liệu bồi thường',
                'db_table': 'claimdocuments',
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đánh giá')),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Điểm rủi ro')),
                ('risk_level', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('very_high', 'Rất cao')], max_length=10, verbose_name='Mức độ rủi ro')),
                ('ai_model_version', models.CharField(max_length=50, verbose_name='Phiên bản mô hình AI')),
                ('assessment_details', models.JSONField(default=dict, verbose_name='Chi tiết đánh giá')),
            ],
            options={
                'verbose_name': 'Đánh giá rủi ro',
                'verbose_name_plural': 'Đánh giá rủi ro',
                'db_table': 'riskassessments',
            },
        ),
    ]
