# Generated by Django 5.2.5 on 2025-11-06 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_initial'),
        ('policies', '0004_remove_policy_claimed_amount_policy_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claim_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Số yêu cầu bồi thường'),
        ),
        migrations.AddField(
            model_name='claim',
            name='claimed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Tổng số tiền đã chi trả'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Số tiền được duyệt'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='policies.policy', verbose_name='Hợp đồng bảo hiểm'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='requested_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền yêu cầu'),
        ),
        migrations.AlterField(
            model_name='claimdocument',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_documents', to='claims.claim', verbose_name='Yêu cầu bồi thường'),
        ),
        migrations.AlterField(
            model_name='claimdocument',
            name='file_url',
            field=models.FileField(upload_to='', verbose_name='URL file'),
        ),
        migrations.CreateModel(
            name='ClaimMedicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(choices=[('inpatient', 'Điều trị nội trú'), ('outpatient', 'Điều trị ngoại trú'), ('surgery', 'Phẫu thuật'), ('death', 'Tử vong'), ('other', 'Khác')], max_length=20, verbose_name='Loại điều trị')),
                ('hospital_name', models.CharField(max_length=255, verbose_name='Tên bệnh viện / cơ sở y tế')),
                ('doctor_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bác sĩ điều trị')),
                ('hospital_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ bệnh viện')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='Chẩn đoán / bệnh lý')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='Ngày nhập viện')),
                ('discharge_date', models.DateField(blank=True, null=True, verbose_name='Ngày xuất viện')),
                ('total_treatment_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Tổng chi phí điều trị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_medical_info', to='claims.claim')),
            ],
            options={
                'verbose_name': 'Thông tin y tế',
                'verbose_name_plural': 'Thông tin y tế',
                'db_table': 'claim_medical_info',
            },
        ),
        migrations.CreateModel(
            name='ClaimPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Ngân hàng')),
                ('account_number', models.CharField(max_length=30, verbose_name='Số tài khoản')),
                ('account_holder_name', models.CharField(max_length=100, verbose_name='Chủ tài khoản')),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='claims.claim')),
            ],
            options={
                'verbose_name': 'Tài khoản nhận bồi thường',
                'verbose_name_plural': 'Tài khoản nhận bồi thường',
                'db_table': 'claim_payment',
            },
        ),
    ]
