# Generated by Django 5.2.5 on 2025-08-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True, verbose_name='Tên sản phẩm')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('coverage_details', models.TextField(verbose_name='Chi tiết bảo hiểm')),
                ('terms_and_conditions', models.TextField(verbose_name='Điều khoản và điều kiện')),
                ('premium_base_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Phí bảo hiểm cơ bản')),
                ('currency', models.CharField(choices=[('VND', 'Việt Nam Đồng'), ('USD', 'US Dollar')], default='VND', max_length=5, verbose_name='Đơn vị tiền tệ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Sản phẩm bảo hiểm',
                'verbose_name_plural': 'Sản phẩm bảo hiểm',
                'db_table': 'insurance_product',
            },
        ),
    ]
