# Generated by Django 5.2.5 on 2025-10-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='max_claim_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Mức chi trả tối đa'),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='product_type',
            field=models.CharField(choices=[('basic', 'Gói Cơ bản'), ('standard', 'Gói Tiêu chuẩn'), ('premium', 'Gói Cao cấp')], default='standard', max_length=20, verbose_name='Loại gói bảo hiểm'),
        ),
    ]
