# Generated by Django 5.2.5 on 2025-11-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_products', '0002_insuranceproduct_max_claim_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='agent_commission_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Hoa hồng cho CTV (%)'),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='max_claim_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Mức chi trả tối đa'),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='premium_base_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Phí bảo hiểm cơ bản'),
        ),
    ]
