# Generated by Django 5.2.7 on 2025-10-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Nội dung thông báo')),
                ('notification_type', models.CharField(choices=[('policy_update', 'Cập nhật hợp đồng'), ('claim_status', 'Trạng thái bồi thường'), ('payment_reminder', 'Nhắc nhở thanh toán'), ('promotion', 'Khuyến mãi'), ('other', 'Khác')], max_length=20, verbose_name='Loại thông báo')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gửi')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'db_table': 'notification',
                'ordering': ['-sent_at'],
            },
        ),
    ]
